// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package server;

public final class Server_Stub
    extends java.rmi.server.RemoteStub
    implements server_board.ServerBoard, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_connect_0;
    private static java.lang.reflect.Method $method_disconnect_1;
    private static java.lang.reflect.Method $method_recieveMsg_2;
    
    static {
	try {
	    $method_connect_0 = server_board.ServerBoard.class.getMethod("connect", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	    $method_disconnect_1 = server_board.ServerBoard.class.getMethod("disconnect", new java.lang.Class[] {java.lang.String.class});
	    $method_recieveMsg_2 = server_board.ServerBoard.class.getMethod("recieveMsg", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public Server_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of connect(String, String)
    public java.lang.Object connect(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_connect_0, new java.lang.Object[] {$param_String_1, $param_String_2}, -1062598680554320576L);
	    return ((java.lang.Object) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of disconnect(String)
    public java.lang.Object disconnect(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_disconnect_1, new java.lang.Object[] {$param_String_1}, -4554075359324365165L);
	    return ((java.lang.Object) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of recieveMsg(String, String)
    public java.lang.Object recieveMsg(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_recieveMsg_2, new java.lang.Object[] {$param_String_1, $param_String_2}, 8970219156848388121L);
	    return ((java.lang.Object) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
